agents:
  image: docker.elastic.co/ci-agent-images/enterprise-search/rbenv-buildkite-agent:latest

defaultTimeoutInMinutes: 45
steps:
  - label: ":safety_vest: Connectors Tests"
    commands:
      - "./.buildkite/scripts/run_command.sh test"
    artifact_paths:
      - "index.html"
  - label: ":wrench: Linter"
    commands:
      - "./.buildkite/scripts/run_command.sh linter"
  - label: ":package: Docker"
    commands:
      - "./.buildkite/scripts/run_command.sh docker"
  - label: ":package: Packaging"
    commands:
      - "./.buildkite/scripts/run_command.sh packaging"
    artifact_paths:
      - "app/.gems/*.gem"
