agents:
  image: "docker.elastic.co/swiftype/ent-search-ci-dev-base-20220124:latest"

defaultTimeoutInMinutes: 45
steps:
  - label: ":safety_vest: Connectors Tests"
    commands:
      - 'make install test'
    artifact_paths:
      - "index.html"
  - label: ":wrench: Linter"
    commands:
      - 'make install lint'
  - label: ":package: Docker"
    commands:
      - 'make build-docker'
  - label: ":package: Packaging"
    commands:
      - 'curl -L -o yq https://github.com/mikefarah/yq/releases/download/v4.21.1/yq_linux_amd64'
      - 'chmod +x yq'
      - 'YQ=`realpath yq` make install build_service build_service_gem'
      - 'gem install .gems/connectors_service-8.*'
    artifact_paths:
      - "app/.gems/*.gem"
