defaultTimeoutInMinutes: 45
steps:
  - label: ":safety_vest: Connectors Tests"
    agents:
      image: docker.elastic.co/ci-agent-images/enterprise-search/rbenv-buildkite-agent:latest
    commands:
      - "./.buildkite/scripts/run_command.sh test"
    artifact_paths:
      - "coverage/index.html"
  - label: ":wrench: Linter"
    agents:
      image: docker.elastic.co/ci-agent-images/enterprise-search/rbenv-buildkite-agent:latest
    commands:
      - "./.buildkite/scripts/run_command.sh linter"
  - label: ":package: Docker"
    commands:
      - "echo 'test docker output'"
      # - "./.buildkite/scripts/run_command.sh docker"
  - label: ":package: Packaging"
    agents:
      image: docker.elastic.co/ci-agent-images/enterprise-search/rbenv-buildkite-agent:latest
    commands:
      - "./.buildkite/scripts/run_command.sh packaging"
    artifact_paths:
      - "app/.gems/*.gem"
