# general metadata
version: "8.2.0-1648647994"
repository: "git@github.com:elastic/connectors.git"
revision: "1e919d0fff2e4d03b5d4a1f606e282a0f9851b8f"
# web service
http:
  port: 9292
  api_key: changeme
  deactivate_auth: false
  connector: share_point
