# general metadata
version: "8.3.0.0-20220429T155054Z"
repository: "git@github.com:elastic/connectors.git"
revision: "0e21b5745124afd30894324602739d44764b4393"
# web service
http:
  host: 0.0.0.0
  port: 9292
  api_key: foobar
  deactivate_auth: true
  connector: confluence_cloud
