# general metadata
version: "8.3.0.0-1649773636"
repository: "https://github.com/elastic/connectors.git"
revision: "da2d1d33e6019c411df39f6bf4d8184921a0d23c"
# web service
http:
  host: 0.0.0.0
  port: 9292
  api_key: EC689157C66D4A26902CCCFBD69BAA93
  deactivate_auth: false
  connector: share_point
