# general metadata
version: "8.3.0.0"
repository: "https://github.com/elastic/connectors.git"
revision: "f71bd39924bd517b87ea6232daf7821cb25f632e"
# web service
http:
  host: 0.0.0.0
  port: 9292
  api_key: EC689157C66D4A26902CCCFBD69BAA93
  deactivate_auth: false
  connector: share_point
