# general metadata
version: "8.2.0-1648721082"
repository: "git@github.com:elastic/connectors.git"
revision: "48e7312286983c0197f7c3027487c4bfd6833090"
# web service
http:
  host: 0.0.0.0
  port: 9292
  api_key: EC689157C66D4A26902CCCFBD69BAA93
  deactivate_auth: false
  connector: share_point
