# general metadata
version: "8.3.0.0-20220429T103037Z"
repository: "git@github.com:elastic/connectors.git"
revision: "a6d15d99a58a8d0e79ca1f77ceed78e734f394db"
# web service
http:
  host: 0.0.0.0
  port: 9292
  api_key: foobar
  deactivate_auth: true
  connector: confluence_cloud
